if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "2.2.2"
  gem "cloudcannon-jekyll-bookshop", "2.2.2"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.9.2"
end

gem "webrick", "~> 1.8"